#!/usr/bin/env ruby

require 'date'
require 'net/http'
require 'fileutils'

# get id
user = IO.popen("whoami", "r+").gets.chomp
program = ARGV[0].to_s
idfile = "/Users/#{user}/Library/Gyazo/id"
old_idfile = File.dirname(program) + "/gyazo.app/Contents/Resources/id"
rectfile = "/Users/#{user}/Pictures/Gyazo/rect"

id = ''
if File.exist?(idfile) then
  id = File.read(idfile).chomp
elsif File.exist?(old_idfile) then
  id = File.read(old_idfile).chomp
end

rect = { on: false }
if File.exist?(rectfile) then
  rect = eval(File.read(rectfile))
end

# capture png file

unless FileTest.exist?("/Users/#{user}/Pictures/Gyazo")
  FileUtils.mkdir_p("/Users/#{user}/Pictures/Gyazo")
end
tmpfile = "/Users/#{user}/Pictures/Gyazo/スクリーンショット #{Time.now.strftime("%Y-%m-%d %H.%M.%S")}.png"
imagefile = ARGV[1]

if rect[:on]
  system "screencapture -R#{rect[:x]},#{rect[:y]},#{rect[:width]},#{rect[:height]} \"#{tmpfile}\""
  if File.exist?(tmpfile) then
    system "osascript -e 'on run args' -e 'set the clipboard to POSIX file (first item of args)' -e end '#{tmpfile}'"
  end
  exit
end

if imagefile && File.exist?(imagefile) then
  system "sips -s format png \"#{imagefile}\" --out \"#{tmpfile}\""
else
  system "screencapture -i \"#{tmpfile}\""
  if File.exist?(tmpfile) then
    system "sips -d profile --deleteColorManagementProperties \"#{tmpfile}\""
    dpiWidth    = `sips -g dpiWidth "#{tmpfile}" | awk '/:/ {print $2}'`
    dpiHeight   = `sips -g dpiHeight "#{tmpfile}" | awk '/:/ {print $2}'`
    pixelWidth  = `sips -g pixelWidth "#{tmpfile}" | awk '/:/ {print $2}'`
    pixelHeight = `sips -g pixelHeight "#{tmpfile}" | awk '/:/ {print $2}'`
    if (dpiWidth.to_f > 72.0 and dpiHeight.to_f > 72.0) then
        width  =  pixelWidth.to_f * 72.0 / dpiWidth.to_f
        height =  pixelHeight.to_f* 72.0 / dpiHeight.to_f
        system "sips -s dpiWidth 72 -s dpiHeight 72 -z #{height} #{width} \"#{tmpfile}\""
    end
    system "osascript -e 'on run args' -e 'set the clipboard to POSIX file (first item of args)' -e end '#{tmpfile}'"
  end
end
